// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://dummy:password@localhost:5432/dummy",
    // Prisma's config expects `shadowDatabaseUrl` for an alternate DB URL
    // (previously `directUrl` is not a known property here)
    shadowDatabaseUrl: process.env["DIRECT_URL"] || "postgresql://dummy:password@localhost:5432/dummy",
  },
});
